# Generated by Django 3.0.7 on 2020-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200923_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='std',
            field=models.CharField(max_length=50),
        ),
    ]
